name: validate-script

on:
  push:
    branches:
      - main
    paths:
      - 'Install.ps1'
  schedule:
    - cron:  '0 10 * * 2'
  workflow_dispatch:
    branches:
        - main

jobs:
  validate:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Run Install.ps1
      - name: Run Install.ps1
        shell: powershell
        run: |
          . .\Install.ps1

      # Run Pester tests
      - name: Validate with Pester
        shell: powershell
        run: |
          . .\ci\Install.ps1
          . .\ci\Tests.ps1

  tag:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Import GPG key
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPGKEY }}
          passphrase: ${{ secrets.GPGPASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_config_global: true
          git_tag_gpgsign: true
          git_push_gpgsign: false
          git_committer_name: ${{ secrets.COMMIT_USER }}
          git_committer_email: ${{ secrets.COMMIT_EMAIL }}

      # Push tag
      - name: Push tag
        shell: bash
        run: |
          DATEF=`date +%Y.%m.%d`
          git tag -a "v$DATEF.$GITHUB_RUN_NUMBER" -m "Validate script v$DATEF.$GITHUB_RUN_NUMBER"
          git push origin "v$DATEF.$GITHUB_RUN_NUMBER"
